CXXFLAGS = -g -std=c++17 -Wall -Wextra -Weffc++ -Wc++0x-compat -Wc++11-compat -Wc++14-compat -Waggressive-loop-optimizations \
-Walloc-zero -Walloca -Walloca-larger-than=8192 -Warray-bounds -Wcast-align -Wcast-qual -Wchar-subscripts \
-Wconditionally-supported -Wconversion -Wctor-dtor-privacy -Wdangling-else -Wduplicated-branches -Wempty-body -Wfloat-equal \
-Wformat-nonliteral -Wformat-security -Wformat-signedness -Wformat=2 -Wformat-overflow=2 -Wformat-truncation=2 -Winline \
-Wlarger-than=8192 -Wvla-larger-than=8192 -Wlogical-op -Wmissing-declarations -Wnon-virtual-dtor -Wopenmp-simd \
-Woverloaded-virtual -Wpacked -Wpointer-arith -Wredundant-decls  -Wrestrict -Wshadow -Wsign-promo -Wstack-usage=8192 \
-Wstrict-null-sentinel -Wstrict-overflow=2 -Wstringop-overflow=4 -Wsuggest-attribute=noreturn -Wsuggest-final-types \
-Wsuggest-override -Wswitch-default -Wswitch-enum -Wsync-nand -Wundef -Wunreachable-code -Wunused -Wvariadic-macros \
-Wno-literal-suffix -Wno-missing-field-initializers -Wnarrowing -Wno-old-style-cast -Wvarargs -Waligned-new \
-Walloc-size-larger-than=1073741824 -Walloc-zero -Walloca -Walloca-larger-than=8192 -Wdangling-else \
-Wduplicated-branches -Wformat-overflow=2 -Wformat-truncation=2 -Wmissing-attributes -Wmultistatement-macros -Wrestrict \
-Wshadow=global -Wsuggest-attribute=malloc -fcheck-new -fsized-deallocation -fstack-check -fstrict-overflow \
-flto-odr-type-merging -fno-omit-frame-pointer -Wno-unknown-pragmas

ProjectPath = C:\Users\gold4\Desktop\MIPT-main\First Course\First Semester\Dedinsky Course\CPU emulator\lib\stack

SrcDir = src
IncDir = include
BinDir = bin
LibDir = ../

ColorsDir = $(LibDir)/colors
DebugDir = $(LibDir)/debug

HashBinDir = $(LibDir)/hash/bin
HashIncDir = $(LibDir)/hash/include

$(BinDir)/stack.o: 	$(SrcDir)/stack.cpp $(IncDir)/stack.h $(IncDir)/settings.h \
					$(DebugDir)/debug.h $(HashIncDir)/hash.h $(LibDir)/colors/colors.h
	g++ -c $(SrcDir)/stack.cpp $(CXXFLAGS) -o $(BinDir)/stack.o

$(HashBinDir)/hash.o: 
	"$(MAKE)" -C "$(ProjectPath)/$(LibDir)/hash/"

.PHONY: init
init:
	mkdir bin
